# Generated by Django 4.0.5 on 2022-06-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Moviedata',
        ),
    ]
