# Generated by Django 4.0.5 on 2022-06-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_durattion_moviedata_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='movietype',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
