# Generated by Django 4.0.5 on 2022-06-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviedata_movietype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='movie.jpg', upload_to='moviepics'),
        ),
    ]
